# Generated by Django 5.0.1 on 2024-02-16 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_at'], 'verbose_name': 'Comments', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
